// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="TrellisBuilder_TrellisBuilder,hls_ip_2022_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7vx485t-ffg1761-3,HLS_INPUT_CLOCK=11.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.766000,HLS_SYN_LAT=76,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=1592,HLS_SYN_LUT=7335,HLS_VERSION=2022_1}" *)

module TrellisBuilder (
        ap_clk,
        ap_rst,
        In_EncodeStream,
        Outdecode_i,
        Outdecode_o,
        Outdecode_o_ap_vld
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;

input   ap_clk;
input   ap_rst;
input  [191:0] In_EncodeStream;
input  [63:0] Outdecode_i;
output  [63:0] Outdecode_o;
output   Outdecode_o_ap_vld;

reg Outdecode_o_ap_vld;

(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [63:0] p_Result_s_fu_1199_p5;
reg   [63:0] p_Result_s_reg_2091;
wire    ap_CS_fsm_state3;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_ap_start;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_ap_done;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_ap_idle;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_ap_ready;
wire   [5:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_11_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_11_out_ap_vld;
wire   [5:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_10_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_10_out_ap_vld;
wire   [5:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_9_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_9_out_ap_vld;
wire   [5:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_8_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_8_out_ap_vld;
wire   [5:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_7_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_7_out_ap_vld;
wire   [5:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_6_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_6_out_ap_vld;
wire   [5:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_11_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_11_out_ap_vld;
wire   [5:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_10_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_10_out_ap_vld;
wire   [5:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_9_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_9_out_ap_vld;
wire   [5:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_8_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_8_out_ap_vld;
wire   [5:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_7_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_7_out_ap_vld;
wire   [5:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_6_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_6_out_ap_vld;
wire   [5:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_11_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_11_out_ap_vld;
wire   [5:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_10_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_10_out_ap_vld;
wire   [5:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_9_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_9_out_ap_vld;
wire   [5:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_8_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_8_out_ap_vld;
wire   [5:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_7_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_7_out_ap_vld;
wire   [5:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_6_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_6_out_ap_vld;
wire   [5:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_11_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_11_out_ap_vld;
wire   [5:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_10_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_10_out_ap_vld;
wire   [5:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_9_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_9_out_ap_vld;
wire   [5:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_8_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_8_out_ap_vld;
wire   [5:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_7_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_7_out_ap_vld;
wire   [5:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_6_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_6_out_ap_vld;
wire   [5:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_5_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_5_out_ap_vld;
wire   [5:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_4_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_4_out_ap_vld;
wire   [5:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_3_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_3_out_ap_vld;
wire   [5:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_2_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_2_out_ap_vld;
wire   [5:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_1_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_1_out_ap_vld;
wire   [5:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_out_ap_vld;
wire   [5:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_5_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_5_out_ap_vld;
wire   [5:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_4_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_4_out_ap_vld;
wire   [5:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_3_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_3_out_ap_vld;
wire   [5:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_2_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_2_out_ap_vld;
wire   [5:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_1_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_1_out_ap_vld;
wire   [5:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_out_ap_vld;
wire   [5:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_5_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_5_out_ap_vld;
wire   [5:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_4_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_4_out_ap_vld;
wire   [5:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_3_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_3_out_ap_vld;
wire   [5:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_2_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_2_out_ap_vld;
wire   [5:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_1_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_1_out_ap_vld;
wire   [5:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_out_ap_vld;
wire   [5:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_5_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_5_out_ap_vld;
wire   [5:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_4_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_4_out_ap_vld;
wire   [5:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_3_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_3_out_ap_vld;
wire   [5:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_2_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_2_out_ap_vld;
wire   [5:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_1_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_1_out_ap_vld;
wire   [5:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_out_ap_vld;
wire   [0:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_47_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_47_out_ap_vld;
wire   [0:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_46_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_46_out_ap_vld;
wire   [0:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_45_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_45_out_ap_vld;
wire   [0:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_44_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_44_out_ap_vld;
wire   [0:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_43_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_43_out_ap_vld;
wire   [0:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_42_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_42_out_ap_vld;
wire   [0:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_41_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_41_out_ap_vld;
wire   [0:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_40_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_40_out_ap_vld;
wire   [0:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_39_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_39_out_ap_vld;
wire   [0:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_38_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_38_out_ap_vld;
wire   [0:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_37_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_37_out_ap_vld;
wire   [0:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_36_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_36_out_ap_vld;
wire   [0:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_35_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_35_out_ap_vld;
wire   [0:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_34_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_34_out_ap_vld;
wire   [0:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_33_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_33_out_ap_vld;
wire   [0:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_32_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_32_out_ap_vld;
wire   [0:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_31_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_31_out_ap_vld;
wire   [0:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_30_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_30_out_ap_vld;
wire   [0:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_29_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_29_out_ap_vld;
wire   [0:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_28_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_28_out_ap_vld;
wire   [0:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_27_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_27_out_ap_vld;
wire   [0:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_26_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_26_out_ap_vld;
wire   [0:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_25_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_25_out_ap_vld;
wire   [0:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_24_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_24_out_ap_vld;
wire   [0:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_23_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_23_out_ap_vld;
wire   [0:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_22_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_22_out_ap_vld;
wire   [0:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_21_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_21_out_ap_vld;
wire   [0:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_20_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_20_out_ap_vld;
wire   [0:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_19_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_19_out_ap_vld;
wire   [0:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_18_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_18_out_ap_vld;
wire   [0:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_17_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_17_out_ap_vld;
wire   [0:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_16_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_16_out_ap_vld;
wire   [0:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_15_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_15_out_ap_vld;
wire   [0:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_14_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_14_out_ap_vld;
wire   [0:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_13_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_13_out_ap_vld;
wire   [0:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_12_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_12_out_ap_vld;
wire   [0:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_11_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_11_out_ap_vld;
wire   [0:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_10_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_10_out_ap_vld;
wire   [0:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_9_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_9_out_ap_vld;
wire   [0:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_8_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_8_out_ap_vld;
wire   [0:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_7_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_7_out_ap_vld;
wire   [0:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_6_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_6_out_ap_vld;
wire   [0:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_5_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_5_out_ap_vld;
wire   [0:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_4_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_4_out_ap_vld;
wire   [0:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_3_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_3_out_ap_vld;
wire   [0:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_2_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_2_out_ap_vld;
wire   [0:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_1_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_1_out_ap_vld;
wire   [0:0] grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_out;
wire    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_out_ap_vld;
wire    grp_TrellisBuilder_Pipeline_VITIS_LOOP_1452_1_fu_711_ap_start;
wire    grp_TrellisBuilder_Pipeline_VITIS_LOOP_1452_1_fu_711_ap_done;
wire    grp_TrellisBuilder_Pipeline_VITIS_LOOP_1452_1_fu_711_ap_idle;
wire    grp_TrellisBuilder_Pipeline_VITIS_LOOP_1452_1_fu_711_ap_ready;
wire   [63:0] grp_TrellisBuilder_Pipeline_VITIS_LOOP_1452_1_fu_711_p_Val2_1_out;
wire    grp_TrellisBuilder_Pipeline_VITIS_LOOP_1452_1_fu_711_p_Val2_1_out_ap_vld;
reg   [2:0] Bucket_V_reg_579;
reg    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_TrellisBuilder_Pipeline_VITIS_LOOP_1452_1_fu_711_ap_start_reg;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
reg   [4:0] ap_NS_fsm;
wire    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
#0 grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_ap_start_reg = 1'b0;
#0 grp_TrellisBuilder_Pipeline_VITIS_LOOP_1452_1_fu_711_ap_start_reg = 1'b0;
end

TrellisBuilder_TrellisBuilder_Pipeline_TrellisLoop grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_ap_start),
    .ap_done(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_ap_done),
    .ap_idle(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_ap_idle),
    .ap_ready(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_ap_ready),
    .In_EncodeStream(In_EncodeStream),
    .prevState_V_2_11_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_11_out),
    .prevState_V_2_11_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_11_out_ap_vld),
    .prevState_V_2_10_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_10_out),
    .prevState_V_2_10_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_10_out_ap_vld),
    .prevState_V_2_9_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_9_out),
    .prevState_V_2_9_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_9_out_ap_vld),
    .prevState_V_2_8_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_8_out),
    .prevState_V_2_8_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_8_out_ap_vld),
    .prevState_V_2_7_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_7_out),
    .prevState_V_2_7_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_7_out_ap_vld),
    .prevState_V_2_6_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_6_out),
    .prevState_V_2_6_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_6_out_ap_vld),
    .prevState_V_0_11_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_11_out),
    .prevState_V_0_11_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_11_out_ap_vld),
    .prevState_V_0_10_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_10_out),
    .prevState_V_0_10_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_10_out_ap_vld),
    .prevState_V_0_9_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_9_out),
    .prevState_V_0_9_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_9_out_ap_vld),
    .prevState_V_0_8_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_8_out),
    .prevState_V_0_8_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_8_out_ap_vld),
    .prevState_V_0_7_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_7_out),
    .prevState_V_0_7_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_7_out_ap_vld),
    .prevState_V_0_6_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_6_out),
    .prevState_V_0_6_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_6_out_ap_vld),
    .prevState_V_3_11_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_11_out),
    .prevState_V_3_11_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_11_out_ap_vld),
    .prevState_V_3_10_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_10_out),
    .prevState_V_3_10_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_10_out_ap_vld),
    .prevState_V_3_9_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_9_out),
    .prevState_V_3_9_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_9_out_ap_vld),
    .prevState_V_3_8_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_8_out),
    .prevState_V_3_8_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_8_out_ap_vld),
    .prevState_V_3_7_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_7_out),
    .prevState_V_3_7_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_7_out_ap_vld),
    .prevState_V_3_6_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_6_out),
    .prevState_V_3_6_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_6_out_ap_vld),
    .prevState_V_1_11_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_11_out),
    .prevState_V_1_11_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_11_out_ap_vld),
    .prevState_V_1_10_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_10_out),
    .prevState_V_1_10_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_10_out_ap_vld),
    .prevState_V_1_9_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_9_out),
    .prevState_V_1_9_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_9_out_ap_vld),
    .prevState_V_1_8_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_8_out),
    .prevState_V_1_8_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_8_out_ap_vld),
    .prevState_V_1_7_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_7_out),
    .prevState_V_1_7_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_7_out_ap_vld),
    .prevState_V_1_6_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_6_out),
    .prevState_V_1_6_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_6_out_ap_vld),
    .prevState_V_0_5_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_5_out),
    .prevState_V_0_5_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_5_out_ap_vld),
    .prevState_V_0_4_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_4_out),
    .prevState_V_0_4_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_4_out_ap_vld),
    .prevState_V_0_3_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_3_out),
    .prevState_V_0_3_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_3_out_ap_vld),
    .prevState_V_0_2_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_2_out),
    .prevState_V_0_2_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_2_out_ap_vld),
    .prevState_V_0_1_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_1_out),
    .prevState_V_0_1_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_1_out_ap_vld),
    .prevState_V_0_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_out),
    .prevState_V_0_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_out_ap_vld),
    .prevState_V_2_5_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_5_out),
    .prevState_V_2_5_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_5_out_ap_vld),
    .prevState_V_2_4_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_4_out),
    .prevState_V_2_4_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_4_out_ap_vld),
    .prevState_V_2_3_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_3_out),
    .prevState_V_2_3_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_3_out_ap_vld),
    .prevState_V_2_2_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_2_out),
    .prevState_V_2_2_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_2_out_ap_vld),
    .prevState_V_2_1_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_1_out),
    .prevState_V_2_1_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_1_out_ap_vld),
    .prevState_V_2_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_out),
    .prevState_V_2_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_out_ap_vld),
    .prevState_V_1_5_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_5_out),
    .prevState_V_1_5_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_5_out_ap_vld),
    .prevState_V_1_4_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_4_out),
    .prevState_V_1_4_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_4_out_ap_vld),
    .prevState_V_1_3_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_3_out),
    .prevState_V_1_3_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_3_out_ap_vld),
    .prevState_V_1_2_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_2_out),
    .prevState_V_1_2_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_2_out_ap_vld),
    .prevState_V_1_1_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_1_out),
    .prevState_V_1_1_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_1_out_ap_vld),
    .prevState_V_1_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_out),
    .prevState_V_1_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_out_ap_vld),
    .prevState_V_3_5_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_5_out),
    .prevState_V_3_5_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_5_out_ap_vld),
    .prevState_V_3_4_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_4_out),
    .prevState_V_3_4_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_4_out_ap_vld),
    .prevState_V_3_3_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_3_out),
    .prevState_V_3_3_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_3_out_ap_vld),
    .prevState_V_3_2_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_2_out),
    .prevState_V_3_2_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_2_out_ap_vld),
    .prevState_V_3_1_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_1_out),
    .prevState_V_3_1_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_1_out_ap_vld),
    .prevState_V_3_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_out),
    .prevState_V_3_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_out_ap_vld),
    .choice_47_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_47_out),
    .choice_47_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_47_out_ap_vld),
    .choice_46_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_46_out),
    .choice_46_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_46_out_ap_vld),
    .choice_45_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_45_out),
    .choice_45_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_45_out_ap_vld),
    .choice_44_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_44_out),
    .choice_44_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_44_out_ap_vld),
    .choice_43_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_43_out),
    .choice_43_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_43_out_ap_vld),
    .choice_42_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_42_out),
    .choice_42_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_42_out_ap_vld),
    .choice_41_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_41_out),
    .choice_41_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_41_out_ap_vld),
    .choice_40_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_40_out),
    .choice_40_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_40_out_ap_vld),
    .choice_39_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_39_out),
    .choice_39_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_39_out_ap_vld),
    .choice_38_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_38_out),
    .choice_38_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_38_out_ap_vld),
    .choice_37_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_37_out),
    .choice_37_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_37_out_ap_vld),
    .choice_36_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_36_out),
    .choice_36_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_36_out_ap_vld),
    .choice_35_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_35_out),
    .choice_35_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_35_out_ap_vld),
    .choice_34_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_34_out),
    .choice_34_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_34_out_ap_vld),
    .choice_33_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_33_out),
    .choice_33_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_33_out_ap_vld),
    .choice_32_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_32_out),
    .choice_32_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_32_out_ap_vld),
    .choice_31_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_31_out),
    .choice_31_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_31_out_ap_vld),
    .choice_30_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_30_out),
    .choice_30_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_30_out_ap_vld),
    .choice_29_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_29_out),
    .choice_29_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_29_out_ap_vld),
    .choice_28_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_28_out),
    .choice_28_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_28_out_ap_vld),
    .choice_27_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_27_out),
    .choice_27_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_27_out_ap_vld),
    .choice_26_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_26_out),
    .choice_26_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_26_out_ap_vld),
    .choice_25_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_25_out),
    .choice_25_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_25_out_ap_vld),
    .choice_24_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_24_out),
    .choice_24_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_24_out_ap_vld),
    .choice_23_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_23_out),
    .choice_23_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_23_out_ap_vld),
    .choice_22_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_22_out),
    .choice_22_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_22_out_ap_vld),
    .choice_21_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_21_out),
    .choice_21_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_21_out_ap_vld),
    .choice_20_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_20_out),
    .choice_20_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_20_out_ap_vld),
    .choice_19_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_19_out),
    .choice_19_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_19_out_ap_vld),
    .choice_18_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_18_out),
    .choice_18_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_18_out_ap_vld),
    .choice_17_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_17_out),
    .choice_17_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_17_out_ap_vld),
    .choice_16_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_16_out),
    .choice_16_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_16_out_ap_vld),
    .choice_15_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_15_out),
    .choice_15_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_15_out_ap_vld),
    .choice_14_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_14_out),
    .choice_14_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_14_out_ap_vld),
    .choice_13_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_13_out),
    .choice_13_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_13_out_ap_vld),
    .choice_12_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_12_out),
    .choice_12_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_12_out_ap_vld),
    .choice_11_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_11_out),
    .choice_11_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_11_out_ap_vld),
    .choice_10_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_10_out),
    .choice_10_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_10_out_ap_vld),
    .choice_9_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_9_out),
    .choice_9_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_9_out_ap_vld),
    .choice_8_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_8_out),
    .choice_8_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_8_out_ap_vld),
    .choice_7_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_7_out),
    .choice_7_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_7_out_ap_vld),
    .choice_6_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_6_out),
    .choice_6_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_6_out_ap_vld),
    .choice_5_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_5_out),
    .choice_5_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_5_out_ap_vld),
    .choice_4_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_4_out),
    .choice_4_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_4_out_ap_vld),
    .choice_3_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_3_out),
    .choice_3_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_3_out_ap_vld),
    .choice_2_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_2_out),
    .choice_2_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_2_out_ap_vld),
    .choice_1_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_1_out),
    .choice_1_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_1_out_ap_vld),
    .choice_out(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_out),
    .choice_out_ap_vld(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_out_ap_vld)
);

TrellisBuilder_TrellisBuilder_Pipeline_VITIS_LOOP_1452_1 grp_TrellisBuilder_Pipeline_VITIS_LOOP_1452_1_fu_711(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_TrellisBuilder_Pipeline_VITIS_LOOP_1452_1_fu_711_ap_start),
    .ap_done(grp_TrellisBuilder_Pipeline_VITIS_LOOP_1452_1_fu_711_ap_done),
    .ap_idle(grp_TrellisBuilder_Pipeline_VITIS_LOOP_1452_1_fu_711_ap_idle),
    .ap_ready(grp_TrellisBuilder_Pipeline_VITIS_LOOP_1452_1_fu_711_ap_ready),
    .p_Result_s(p_Result_s_reg_2091),
    .Bucket_V(Bucket_V_reg_579),
    .choice_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_out),
    .choice_1_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_1_out),
    .choice_2_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_2_out),
    .choice_3_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_3_out),
    .choice_4_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_4_out),
    .choice_5_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_5_out),
    .choice_43_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_43_out),
    .choice_44_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_44_out),
    .choice_45_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_45_out),
    .choice_46_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_46_out),
    .choice_47_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_47_out),
    .choice_42_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_42_out),
    .choice_41_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_41_out),
    .choice_40_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_40_out),
    .choice_39_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_39_out),
    .choice_38_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_38_out),
    .choice_37_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_37_out),
    .choice_36_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_36_out),
    .choice_35_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_35_out),
    .choice_34_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_34_out),
    .choice_33_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_33_out),
    .choice_32_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_32_out),
    .choice_31_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_31_out),
    .choice_30_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_30_out),
    .choice_29_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_29_out),
    .choice_28_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_28_out),
    .choice_27_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_27_out),
    .choice_26_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_26_out),
    .choice_25_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_25_out),
    .choice_24_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_24_out),
    .choice_23_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_23_out),
    .choice_22_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_22_out),
    .choice_21_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_21_out),
    .choice_20_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_20_out),
    .choice_19_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_19_out),
    .choice_18_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_18_out),
    .choice_17_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_17_out),
    .choice_16_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_16_out),
    .choice_15_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_15_out),
    .choice_14_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_14_out),
    .choice_13_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_13_out),
    .choice_12_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_12_out),
    .choice_11_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_11_out),
    .choice_10_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_10_out),
    .choice_9_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_9_out),
    .choice_8_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_8_out),
    .choice_7_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_7_out),
    .choice_6_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_6_out),
    .prevState_V_0_10_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_10_out),
    .prevState_V_1_10_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_10_out),
    .prevState_V_2_4_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_4_out),
    .prevState_V_3_4_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_4_out),
    .prevState_V_0_4_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_4_out),
    .prevState_V_1_4_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_4_out),
    .prevState_V_2_10_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_10_out),
    .prevState_V_3_10_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_10_out),
    .prevState_V_0_9_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_9_out),
    .prevState_V_1_9_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_9_out),
    .prevState_V_2_3_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_3_out),
    .prevState_V_3_3_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_3_out),
    .prevState_V_0_3_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_3_out),
    .prevState_V_1_3_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_3_out),
    .prevState_V_2_9_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_9_out),
    .prevState_V_3_9_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_9_out),
    .prevState_V_0_8_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_8_out),
    .prevState_V_1_8_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_8_out),
    .prevState_V_2_2_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_2_out),
    .prevState_V_3_2_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_2_out),
    .prevState_V_0_2_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_2_out),
    .prevState_V_1_2_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_2_out),
    .prevState_V_2_8_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_8_out),
    .prevState_V_3_8_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_8_out),
    .prevState_V_0_7_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_7_out),
    .prevState_V_1_7_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_7_out),
    .prevState_V_2_1_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_1_out),
    .prevState_V_3_1_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_1_out),
    .prevState_V_0_1_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_1_out),
    .prevState_V_1_1_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_1_out),
    .prevState_V_2_7_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_7_out),
    .prevState_V_3_7_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_7_out),
    .prevState_V_0_6_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_6_out),
    .prevState_V_1_6_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_6_out),
    .prevState_V_2_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_out),
    .prevState_V_3_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_out),
    .prevState_V_0_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_out),
    .prevState_V_1_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_out),
    .prevState_V_2_6_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_6_out),
    .prevState_V_3_6_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_6_out),
    .prevState_V_0_11_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_11_out),
    .prevState_V_1_11_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_11_out),
    .prevState_V_2_5_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_5_out),
    .prevState_V_3_5_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_5_out),
    .prevState_V_0_5_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_5_out),
    .prevState_V_1_5_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_5_out),
    .prevState_V_2_11_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_11_out),
    .prevState_V_3_11_reload(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_11_out),
    .p_Val2_1_out(grp_TrellisBuilder_Pipeline_VITIS_LOOP_1452_1_fu_711_p_Val2_1_out),
    .p_Val2_1_out_ap_vld(grp_TrellisBuilder_Pipeline_VITIS_LOOP_1452_1_fu_711_p_Val2_1_out_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state1)) begin
            grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_ap_start_reg <= 1'b1;
        end else if ((grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_ap_ready == 1'b1)) begin
            grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_TrellisBuilder_Pipeline_VITIS_LOOP_1452_1_fu_711_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_TrellisBuilder_Pipeline_VITIS_LOOP_1452_1_fu_711_ap_start_reg <= 1'b1;
        end else if ((grp_TrellisBuilder_Pipeline_VITIS_LOOP_1452_1_fu_711_ap_ready == 1'b1)) begin
            grp_TrellisBuilder_Pipeline_VITIS_LOOP_1452_1_fu_711_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (~(1'b1 == 1'b1)) begin
        Bucket_V_reg_579 <= 3'd6;
    end else if (~(1'b1 == 1'b1)) begin
        Bucket_V_reg_579 <= 3'd5;
    end else if (~(1'b1 == 1'b1)) begin
        Bucket_V_reg_579 <= 3'd4;
    end else if (~(1'b1 == 1'b1)) begin
        Bucket_V_reg_579 <= 3'd3;
    end else if (~(1'b1 == 1'b1)) begin
        Bucket_V_reg_579 <= 3'd2;
    end else if (~(1'b1 == 1'b1)) begin
        Bucket_V_reg_579 <= 3'd1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        Bucket_V_reg_579 <= 3'd0;
    end else if (((1'b1 == ap_CS_fsm_state3) & ((6'd7 == 6'd0) | ((6'd10 == 6'd0) | ((6'd22 == 6'd0) | ((6'd27 == 6'd0) | ((6'd36 == 6'd0) | ((6'd41 == 6'd0) | ((6'd53 == 6'd0) | (6'd56 == 6'd0)))))))))) begin
        Bucket_V_reg_579 <= 3'd7;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        p_Result_s_reg_2091 <= p_Result_s_fu_1199_p5;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        Outdecode_o_ap_vld = 1'b1;
    end else begin
        Outdecode_o_ap_vld = 1'b0;
    end
end

assign ap_ST_fsm_state1_blk = 1'b0;

always @ (*) begin
    if ((grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_TrellisBuilder_Pipeline_VITIS_LOOP_1452_1_fu_711_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state2 : begin
            if (((grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((grp_TrellisBuilder_Pipeline_VITIS_LOOP_1452_1_fu_711_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Outdecode_o = grp_TrellisBuilder_Pipeline_VITIS_LOOP_1452_1_fu_711_p_Val2_1_out;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_ap_start = grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_ap_start_reg;

assign grp_TrellisBuilder_Pipeline_VITIS_LOOP_1452_1_fu_711_ap_start = grp_TrellisBuilder_Pipeline_VITIS_LOOP_1452_1_fu_711_ap_start_reg;

assign p_Result_s_fu_1199_p5 = {{Outdecode_i[63:62]}, {2'd0}, {Outdecode_i[59:0]}};

endmodule //TrellisBuilder
