-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
-- Version: 2022.1
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity TrellisBuilder is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    In_EncodeStream : IN STD_LOGIC_VECTOR (263 downto 0);
    Outdecode_i : IN STD_LOGIC_VECTOR (87 downto 0);
    Outdecode_o : OUT STD_LOGIC_VECTOR (87 downto 0);
    Outdecode_o_ap_vld : OUT STD_LOGIC );
end;


architecture behav of TrellisBuilder is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "TrellisBuilder_TrellisBuilder,hls_ip_2022_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7vx485t-ffg1761-3,HLS_INPUT_CLOCK=11.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.766000,HLS_SYN_LAT=100,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=1642,HLS_SYN_LUT=8683,HLS_VERSION=2022_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv3_7 : STD_LOGIC_VECTOR (2 downto 0) := "111";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv6_38 : STD_LOGIC_VECTOR (5 downto 0) := "111000";
    constant ap_const_lv6_35 : STD_LOGIC_VECTOR (5 downto 0) := "110101";
    constant ap_const_lv6_29 : STD_LOGIC_VECTOR (5 downto 0) := "101001";
    constant ap_const_lv6_24 : STD_LOGIC_VECTOR (5 downto 0) := "100100";
    constant ap_const_lv6_1B : STD_LOGIC_VECTOR (5 downto 0) := "011011";
    constant ap_const_lv6_16 : STD_LOGIC_VECTOR (5 downto 0) := "010110";
    constant ap_const_lv6_A : STD_LOGIC_VECTOR (5 downto 0) := "001010";
    constant ap_const_lv6_7 : STD_LOGIC_VECTOR (5 downto 0) := "000111";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv3_6 : STD_LOGIC_VECTOR (2 downto 0) := "110";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv32_54 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010100";
    constant ap_const_lv32_55 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010101";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal p_Result_s_fu_1199_p5 : STD_LOGIC_VECTOR (87 downto 0);
    signal p_Result_s_reg_2091 : STD_LOGIC_VECTOR (87 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_ap_start : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_ap_done : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_ap_idle : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_ap_ready : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_11_out : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_11_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_10_out : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_10_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_9_out : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_9_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_8_out : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_8_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_7_out : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_7_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_6_out : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_6_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_11_out : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_11_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_10_out : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_10_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_9_out : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_9_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_8_out : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_8_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_7_out : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_7_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_6_out : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_6_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_11_out : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_11_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_10_out : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_10_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_9_out : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_9_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_8_out : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_8_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_7_out : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_7_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_6_out : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_6_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_11_out : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_11_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_10_out : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_10_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_9_out : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_9_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_8_out : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_8_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_7_out : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_7_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_6_out : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_6_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_5_out : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_5_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_4_out : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_4_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_3_out : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_3_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_2_out : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_2_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_1_out : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_1_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_out : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_5_out : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_5_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_4_out : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_4_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_3_out : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_3_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_2_out : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_2_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_1_out : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_1_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_out : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_5_out : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_5_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_4_out : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_4_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_3_out : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_3_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_2_out : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_2_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_1_out : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_1_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_out : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_5_out : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_5_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_4_out : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_4_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_3_out : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_3_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_2_out : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_2_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_1_out : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_1_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_out : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_47_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_47_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_46_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_46_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_45_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_45_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_44_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_44_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_43_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_43_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_42_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_42_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_41_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_41_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_40_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_40_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_39_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_39_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_38_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_38_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_37_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_37_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_36_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_36_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_35_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_35_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_34_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_34_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_33_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_33_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_32_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_32_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_31_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_31_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_30_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_30_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_29_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_29_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_28_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_28_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_27_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_27_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_26_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_26_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_25_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_25_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_24_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_24_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_23_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_23_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_22_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_22_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_21_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_21_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_20_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_20_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_19_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_19_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_18_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_18_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_17_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_17_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_16_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_16_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_15_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_15_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_14_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_14_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_13_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_13_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_12_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_12_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_11_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_11_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_10_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_10_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_9_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_9_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_8_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_8_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_7_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_7_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_6_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_6_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_5_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_5_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_4_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_4_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_3_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_3_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_2_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_2_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_1_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_1_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_VITIS_LOOP_1452_1_fu_711_ap_start : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_VITIS_LOOP_1452_1_fu_711_ap_done : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_VITIS_LOOP_1452_1_fu_711_ap_idle : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_VITIS_LOOP_1452_1_fu_711_ap_ready : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_VITIS_LOOP_1452_1_fu_711_p_Val2_1_out : STD_LOGIC_VECTOR (87 downto 0);
    signal grp_TrellisBuilder_Pipeline_VITIS_LOOP_1452_1_fu_711_p_Val2_1_out_ap_vld : STD_LOGIC;
    signal Bucket_V_reg_579 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_TrellisBuilder_Pipeline_VITIS_LOOP_1452_1_fu_711_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component TrellisBuilder_TrellisBuilder_Pipeline_TrellisLoop IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        In_EncodeStream : IN STD_LOGIC_VECTOR (263 downto 0);
        prevState_V_2_11_out : OUT STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_2_11_out_ap_vld : OUT STD_LOGIC;
        prevState_V_2_10_out : OUT STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_2_10_out_ap_vld : OUT STD_LOGIC;
        prevState_V_2_9_out : OUT STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_2_9_out_ap_vld : OUT STD_LOGIC;
        prevState_V_2_8_out : OUT STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_2_8_out_ap_vld : OUT STD_LOGIC;
        prevState_V_2_7_out : OUT STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_2_7_out_ap_vld : OUT STD_LOGIC;
        prevState_V_2_6_out : OUT STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_2_6_out_ap_vld : OUT STD_LOGIC;
        prevState_V_0_11_out : OUT STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_0_11_out_ap_vld : OUT STD_LOGIC;
        prevState_V_0_10_out : OUT STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_0_10_out_ap_vld : OUT STD_LOGIC;
        prevState_V_0_9_out : OUT STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_0_9_out_ap_vld : OUT STD_LOGIC;
        prevState_V_0_8_out : OUT STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_0_8_out_ap_vld : OUT STD_LOGIC;
        prevState_V_0_7_out : OUT STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_0_7_out_ap_vld : OUT STD_LOGIC;
        prevState_V_0_6_out : OUT STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_0_6_out_ap_vld : OUT STD_LOGIC;
        prevState_V_3_11_out : OUT STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_3_11_out_ap_vld : OUT STD_LOGIC;
        prevState_V_3_10_out : OUT STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_3_10_out_ap_vld : OUT STD_LOGIC;
        prevState_V_3_9_out : OUT STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_3_9_out_ap_vld : OUT STD_LOGIC;
        prevState_V_3_8_out : OUT STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_3_8_out_ap_vld : OUT STD_LOGIC;
        prevState_V_3_7_out : OUT STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_3_7_out_ap_vld : OUT STD_LOGIC;
        prevState_V_3_6_out : OUT STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_3_6_out_ap_vld : OUT STD_LOGIC;
        prevState_V_1_11_out : OUT STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_1_11_out_ap_vld : OUT STD_LOGIC;
        prevState_V_1_10_out : OUT STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_1_10_out_ap_vld : OUT STD_LOGIC;
        prevState_V_1_9_out : OUT STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_1_9_out_ap_vld : OUT STD_LOGIC;
        prevState_V_1_8_out : OUT STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_1_8_out_ap_vld : OUT STD_LOGIC;
        prevState_V_1_7_out : OUT STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_1_7_out_ap_vld : OUT STD_LOGIC;
        prevState_V_1_6_out : OUT STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_1_6_out_ap_vld : OUT STD_LOGIC;
        prevState_V_0_5_out : OUT STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_0_5_out_ap_vld : OUT STD_LOGIC;
        prevState_V_0_4_out : OUT STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_0_4_out_ap_vld : OUT STD_LOGIC;
        prevState_V_0_3_out : OUT STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_0_3_out_ap_vld : OUT STD_LOGIC;
        prevState_V_0_2_out : OUT STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_0_2_out_ap_vld : OUT STD_LOGIC;
        prevState_V_0_1_out : OUT STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_0_1_out_ap_vld : OUT STD_LOGIC;
        prevState_V_0_out : OUT STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_0_out_ap_vld : OUT STD_LOGIC;
        prevState_V_2_5_out : OUT STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_2_5_out_ap_vld : OUT STD_LOGIC;
        prevState_V_2_4_out : OUT STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_2_4_out_ap_vld : OUT STD_LOGIC;
        prevState_V_2_3_out : OUT STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_2_3_out_ap_vld : OUT STD_LOGIC;
        prevState_V_2_2_out : OUT STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_2_2_out_ap_vld : OUT STD_LOGIC;
        prevState_V_2_1_out : OUT STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_2_1_out_ap_vld : OUT STD_LOGIC;
        prevState_V_2_out : OUT STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_2_out_ap_vld : OUT STD_LOGIC;
        prevState_V_1_5_out : OUT STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_1_5_out_ap_vld : OUT STD_LOGIC;
        prevState_V_1_4_out : OUT STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_1_4_out_ap_vld : OUT STD_LOGIC;
        prevState_V_1_3_out : OUT STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_1_3_out_ap_vld : OUT STD_LOGIC;
        prevState_V_1_2_out : OUT STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_1_2_out_ap_vld : OUT STD_LOGIC;
        prevState_V_1_1_out : OUT STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_1_1_out_ap_vld : OUT STD_LOGIC;
        prevState_V_1_out : OUT STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_1_out_ap_vld : OUT STD_LOGIC;
        prevState_V_3_5_out : OUT STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_3_5_out_ap_vld : OUT STD_LOGIC;
        prevState_V_3_4_out : OUT STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_3_4_out_ap_vld : OUT STD_LOGIC;
        prevState_V_3_3_out : OUT STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_3_3_out_ap_vld : OUT STD_LOGIC;
        prevState_V_3_2_out : OUT STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_3_2_out_ap_vld : OUT STD_LOGIC;
        prevState_V_3_1_out : OUT STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_3_1_out_ap_vld : OUT STD_LOGIC;
        prevState_V_3_out : OUT STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_3_out_ap_vld : OUT STD_LOGIC;
        choice_47_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        choice_47_out_ap_vld : OUT STD_LOGIC;
        choice_46_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        choice_46_out_ap_vld : OUT STD_LOGIC;
        choice_45_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        choice_45_out_ap_vld : OUT STD_LOGIC;
        choice_44_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        choice_44_out_ap_vld : OUT STD_LOGIC;
        choice_43_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        choice_43_out_ap_vld : OUT STD_LOGIC;
        choice_42_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        choice_42_out_ap_vld : OUT STD_LOGIC;
        choice_41_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        choice_41_out_ap_vld : OUT STD_LOGIC;
        choice_40_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        choice_40_out_ap_vld : OUT STD_LOGIC;
        choice_39_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        choice_39_out_ap_vld : OUT STD_LOGIC;
        choice_38_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        choice_38_out_ap_vld : OUT STD_LOGIC;
        choice_37_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        choice_37_out_ap_vld : OUT STD_LOGIC;
        choice_36_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        choice_36_out_ap_vld : OUT STD_LOGIC;
        choice_35_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        choice_35_out_ap_vld : OUT STD_LOGIC;
        choice_34_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        choice_34_out_ap_vld : OUT STD_LOGIC;
        choice_33_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        choice_33_out_ap_vld : OUT STD_LOGIC;
        choice_32_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        choice_32_out_ap_vld : OUT STD_LOGIC;
        choice_31_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        choice_31_out_ap_vld : OUT STD_LOGIC;
        choice_30_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        choice_30_out_ap_vld : OUT STD_LOGIC;
        choice_29_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        choice_29_out_ap_vld : OUT STD_LOGIC;
        choice_28_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        choice_28_out_ap_vld : OUT STD_LOGIC;
        choice_27_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        choice_27_out_ap_vld : OUT STD_LOGIC;
        choice_26_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        choice_26_out_ap_vld : OUT STD_LOGIC;
        choice_25_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        choice_25_out_ap_vld : OUT STD_LOGIC;
        choice_24_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        choice_24_out_ap_vld : OUT STD_LOGIC;
        choice_23_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        choice_23_out_ap_vld : OUT STD_LOGIC;
        choice_22_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        choice_22_out_ap_vld : OUT STD_LOGIC;
        choice_21_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        choice_21_out_ap_vld : OUT STD_LOGIC;
        choice_20_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        choice_20_out_ap_vld : OUT STD_LOGIC;
        choice_19_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        choice_19_out_ap_vld : OUT STD_LOGIC;
        choice_18_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        choice_18_out_ap_vld : OUT STD_LOGIC;
        choice_17_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        choice_17_out_ap_vld : OUT STD_LOGIC;
        choice_16_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        choice_16_out_ap_vld : OUT STD_LOGIC;
        choice_15_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        choice_15_out_ap_vld : OUT STD_LOGIC;
        choice_14_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        choice_14_out_ap_vld : OUT STD_LOGIC;
        choice_13_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        choice_13_out_ap_vld : OUT STD_LOGIC;
        choice_12_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        choice_12_out_ap_vld : OUT STD_LOGIC;
        choice_11_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        choice_11_out_ap_vld : OUT STD_LOGIC;
        choice_10_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        choice_10_out_ap_vld : OUT STD_LOGIC;
        choice_9_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        choice_9_out_ap_vld : OUT STD_LOGIC;
        choice_8_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        choice_8_out_ap_vld : OUT STD_LOGIC;
        choice_7_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        choice_7_out_ap_vld : OUT STD_LOGIC;
        choice_6_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        choice_6_out_ap_vld : OUT STD_LOGIC;
        choice_5_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        choice_5_out_ap_vld : OUT STD_LOGIC;
        choice_4_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        choice_4_out_ap_vld : OUT STD_LOGIC;
        choice_3_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        choice_3_out_ap_vld : OUT STD_LOGIC;
        choice_2_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        choice_2_out_ap_vld : OUT STD_LOGIC;
        choice_1_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        choice_1_out_ap_vld : OUT STD_LOGIC;
        choice_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        choice_out_ap_vld : OUT STD_LOGIC );
    end component;


    component TrellisBuilder_TrellisBuilder_Pipeline_VITIS_LOOP_1452_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        p_Result_s : IN STD_LOGIC_VECTOR (87 downto 0);
        Bucket_V : IN STD_LOGIC_VECTOR (2 downto 0);
        choice_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        choice_1_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        choice_2_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        choice_3_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        choice_4_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        choice_5_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        choice_47_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        choice_46_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        choice_45_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        choice_44_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        choice_43_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        choice_42_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        choice_41_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        choice_40_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        choice_39_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        choice_38_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        choice_37_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        choice_36_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        choice_35_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        choice_34_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        choice_33_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        choice_32_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        choice_31_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        choice_30_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        choice_29_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        choice_28_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        choice_27_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        choice_26_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        choice_25_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        choice_24_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        choice_23_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        choice_22_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        choice_21_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        choice_20_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        choice_19_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        choice_18_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        choice_17_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        choice_16_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        choice_15_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        choice_14_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        choice_13_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        choice_12_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        choice_11_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        choice_10_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        choice_9_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        choice_8_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        choice_7_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        choice_6_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        prevState_V_0_10_reload : IN STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_1_10_reload : IN STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_2_4_reload : IN STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_3_4_reload : IN STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_0_4_reload : IN STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_1_4_reload : IN STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_2_10_reload : IN STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_3_10_reload : IN STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_0_9_reload : IN STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_1_9_reload : IN STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_2_3_reload : IN STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_3_3_reload : IN STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_0_3_reload : IN STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_1_3_reload : IN STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_2_9_reload : IN STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_3_9_reload : IN STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_0_8_reload : IN STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_1_8_reload : IN STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_2_2_reload : IN STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_3_2_reload : IN STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_0_2_reload : IN STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_1_2_reload : IN STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_2_8_reload : IN STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_3_8_reload : IN STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_0_7_reload : IN STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_1_7_reload : IN STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_2_1_reload : IN STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_3_1_reload : IN STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_0_1_reload : IN STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_1_1_reload : IN STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_2_7_reload : IN STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_3_7_reload : IN STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_0_6_reload : IN STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_1_6_reload : IN STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_2_reload : IN STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_3_reload : IN STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_0_reload : IN STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_1_reload : IN STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_2_6_reload : IN STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_3_6_reload : IN STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_0_11_reload : IN STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_1_11_reload : IN STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_2_5_reload : IN STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_3_5_reload : IN STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_0_5_reload : IN STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_1_5_reload : IN STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_2_11_reload : IN STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_3_11_reload : IN STD_LOGIC_VECTOR (5 downto 0);
        p_Val2_1_out : OUT STD_LOGIC_VECTOR (87 downto 0);
        p_Val2_1_out_ap_vld : OUT STD_LOGIC );
    end component;



begin
    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609 : component TrellisBuilder_TrellisBuilder_Pipeline_TrellisLoop
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_ap_start,
        ap_done => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_ap_done,
        ap_idle => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_ap_idle,
        ap_ready => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_ap_ready,
        In_EncodeStream => In_EncodeStream,
        prevState_V_2_11_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_11_out,
        prevState_V_2_11_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_11_out_ap_vld,
        prevState_V_2_10_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_10_out,
        prevState_V_2_10_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_10_out_ap_vld,
        prevState_V_2_9_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_9_out,
        prevState_V_2_9_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_9_out_ap_vld,
        prevState_V_2_8_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_8_out,
        prevState_V_2_8_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_8_out_ap_vld,
        prevState_V_2_7_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_7_out,
        prevState_V_2_7_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_7_out_ap_vld,
        prevState_V_2_6_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_6_out,
        prevState_V_2_6_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_6_out_ap_vld,
        prevState_V_0_11_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_11_out,
        prevState_V_0_11_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_11_out_ap_vld,
        prevState_V_0_10_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_10_out,
        prevState_V_0_10_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_10_out_ap_vld,
        prevState_V_0_9_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_9_out,
        prevState_V_0_9_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_9_out_ap_vld,
        prevState_V_0_8_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_8_out,
        prevState_V_0_8_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_8_out_ap_vld,
        prevState_V_0_7_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_7_out,
        prevState_V_0_7_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_7_out_ap_vld,
        prevState_V_0_6_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_6_out,
        prevState_V_0_6_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_6_out_ap_vld,
        prevState_V_3_11_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_11_out,
        prevState_V_3_11_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_11_out_ap_vld,
        prevState_V_3_10_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_10_out,
        prevState_V_3_10_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_10_out_ap_vld,
        prevState_V_3_9_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_9_out,
        prevState_V_3_9_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_9_out_ap_vld,
        prevState_V_3_8_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_8_out,
        prevState_V_3_8_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_8_out_ap_vld,
        prevState_V_3_7_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_7_out,
        prevState_V_3_7_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_7_out_ap_vld,
        prevState_V_3_6_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_6_out,
        prevState_V_3_6_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_6_out_ap_vld,
        prevState_V_1_11_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_11_out,
        prevState_V_1_11_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_11_out_ap_vld,
        prevState_V_1_10_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_10_out,
        prevState_V_1_10_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_10_out_ap_vld,
        prevState_V_1_9_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_9_out,
        prevState_V_1_9_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_9_out_ap_vld,
        prevState_V_1_8_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_8_out,
        prevState_V_1_8_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_8_out_ap_vld,
        prevState_V_1_7_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_7_out,
        prevState_V_1_7_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_7_out_ap_vld,
        prevState_V_1_6_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_6_out,
        prevState_V_1_6_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_6_out_ap_vld,
        prevState_V_0_5_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_5_out,
        prevState_V_0_5_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_5_out_ap_vld,
        prevState_V_0_4_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_4_out,
        prevState_V_0_4_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_4_out_ap_vld,
        prevState_V_0_3_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_3_out,
        prevState_V_0_3_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_3_out_ap_vld,
        prevState_V_0_2_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_2_out,
        prevState_V_0_2_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_2_out_ap_vld,
        prevState_V_0_1_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_1_out,
        prevState_V_0_1_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_1_out_ap_vld,
        prevState_V_0_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_out,
        prevState_V_0_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_out_ap_vld,
        prevState_V_2_5_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_5_out,
        prevState_V_2_5_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_5_out_ap_vld,
        prevState_V_2_4_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_4_out,
        prevState_V_2_4_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_4_out_ap_vld,
        prevState_V_2_3_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_3_out,
        prevState_V_2_3_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_3_out_ap_vld,
        prevState_V_2_2_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_2_out,
        prevState_V_2_2_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_2_out_ap_vld,
        prevState_V_2_1_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_1_out,
        prevState_V_2_1_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_1_out_ap_vld,
        prevState_V_2_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_out,
        prevState_V_2_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_out_ap_vld,
        prevState_V_1_5_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_5_out,
        prevState_V_1_5_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_5_out_ap_vld,
        prevState_V_1_4_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_4_out,
        prevState_V_1_4_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_4_out_ap_vld,
        prevState_V_1_3_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_3_out,
        prevState_V_1_3_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_3_out_ap_vld,
        prevState_V_1_2_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_2_out,
        prevState_V_1_2_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_2_out_ap_vld,
        prevState_V_1_1_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_1_out,
        prevState_V_1_1_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_1_out_ap_vld,
        prevState_V_1_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_out,
        prevState_V_1_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_out_ap_vld,
        prevState_V_3_5_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_5_out,
        prevState_V_3_5_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_5_out_ap_vld,
        prevState_V_3_4_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_4_out,
        prevState_V_3_4_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_4_out_ap_vld,
        prevState_V_3_3_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_3_out,
        prevState_V_3_3_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_3_out_ap_vld,
        prevState_V_3_2_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_2_out,
        prevState_V_3_2_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_2_out_ap_vld,
        prevState_V_3_1_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_1_out,
        prevState_V_3_1_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_1_out_ap_vld,
        prevState_V_3_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_out,
        prevState_V_3_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_out_ap_vld,
        choice_47_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_47_out,
        choice_47_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_47_out_ap_vld,
        choice_46_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_46_out,
        choice_46_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_46_out_ap_vld,
        choice_45_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_45_out,
        choice_45_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_45_out_ap_vld,
        choice_44_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_44_out,
        choice_44_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_44_out_ap_vld,
        choice_43_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_43_out,
        choice_43_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_43_out_ap_vld,
        choice_42_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_42_out,
        choice_42_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_42_out_ap_vld,
        choice_41_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_41_out,
        choice_41_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_41_out_ap_vld,
        choice_40_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_40_out,
        choice_40_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_40_out_ap_vld,
        choice_39_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_39_out,
        choice_39_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_39_out_ap_vld,
        choice_38_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_38_out,
        choice_38_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_38_out_ap_vld,
        choice_37_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_37_out,
        choice_37_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_37_out_ap_vld,
        choice_36_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_36_out,
        choice_36_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_36_out_ap_vld,
        choice_35_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_35_out,
        choice_35_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_35_out_ap_vld,
        choice_34_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_34_out,
        choice_34_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_34_out_ap_vld,
        choice_33_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_33_out,
        choice_33_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_33_out_ap_vld,
        choice_32_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_32_out,
        choice_32_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_32_out_ap_vld,
        choice_31_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_31_out,
        choice_31_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_31_out_ap_vld,
        choice_30_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_30_out,
        choice_30_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_30_out_ap_vld,
        choice_29_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_29_out,
        choice_29_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_29_out_ap_vld,
        choice_28_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_28_out,
        choice_28_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_28_out_ap_vld,
        choice_27_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_27_out,
        choice_27_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_27_out_ap_vld,
        choice_26_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_26_out,
        choice_26_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_26_out_ap_vld,
        choice_25_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_25_out,
        choice_25_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_25_out_ap_vld,
        choice_24_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_24_out,
        choice_24_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_24_out_ap_vld,
        choice_23_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_23_out,
        choice_23_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_23_out_ap_vld,
        choice_22_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_22_out,
        choice_22_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_22_out_ap_vld,
        choice_21_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_21_out,
        choice_21_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_21_out_ap_vld,
        choice_20_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_20_out,
        choice_20_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_20_out_ap_vld,
        choice_19_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_19_out,
        choice_19_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_19_out_ap_vld,
        choice_18_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_18_out,
        choice_18_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_18_out_ap_vld,
        choice_17_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_17_out,
        choice_17_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_17_out_ap_vld,
        choice_16_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_16_out,
        choice_16_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_16_out_ap_vld,
        choice_15_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_15_out,
        choice_15_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_15_out_ap_vld,
        choice_14_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_14_out,
        choice_14_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_14_out_ap_vld,
        choice_13_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_13_out,
        choice_13_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_13_out_ap_vld,
        choice_12_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_12_out,
        choice_12_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_12_out_ap_vld,
        choice_11_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_11_out,
        choice_11_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_11_out_ap_vld,
        choice_10_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_10_out,
        choice_10_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_10_out_ap_vld,
        choice_9_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_9_out,
        choice_9_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_9_out_ap_vld,
        choice_8_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_8_out,
        choice_8_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_8_out_ap_vld,
        choice_7_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_7_out,
        choice_7_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_7_out_ap_vld,
        choice_6_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_6_out,
        choice_6_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_6_out_ap_vld,
        choice_5_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_5_out,
        choice_5_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_5_out_ap_vld,
        choice_4_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_4_out,
        choice_4_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_4_out_ap_vld,
        choice_3_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_3_out,
        choice_3_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_3_out_ap_vld,
        choice_2_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_2_out,
        choice_2_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_2_out_ap_vld,
        choice_1_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_1_out,
        choice_1_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_1_out_ap_vld,
        choice_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_out,
        choice_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_out_ap_vld);

    grp_TrellisBuilder_Pipeline_VITIS_LOOP_1452_1_fu_711 : component TrellisBuilder_TrellisBuilder_Pipeline_VITIS_LOOP_1452_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_TrellisBuilder_Pipeline_VITIS_LOOP_1452_1_fu_711_ap_start,
        ap_done => grp_TrellisBuilder_Pipeline_VITIS_LOOP_1452_1_fu_711_ap_done,
        ap_idle => grp_TrellisBuilder_Pipeline_VITIS_LOOP_1452_1_fu_711_ap_idle,
        ap_ready => grp_TrellisBuilder_Pipeline_VITIS_LOOP_1452_1_fu_711_ap_ready,
        p_Result_s => p_Result_s_reg_2091,
        Bucket_V => Bucket_V_reg_579,
        choice_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_out,
        choice_1_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_1_out,
        choice_2_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_2_out,
        choice_3_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_3_out,
        choice_4_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_4_out,
        choice_5_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_5_out,
        choice_47_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_47_out,
        choice_46_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_46_out,
        choice_45_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_45_out,
        choice_44_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_44_out,
        choice_43_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_43_out,
        choice_42_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_42_out,
        choice_41_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_41_out,
        choice_40_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_40_out,
        choice_39_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_39_out,
        choice_38_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_38_out,
        choice_37_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_37_out,
        choice_36_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_36_out,
        choice_35_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_35_out,
        choice_34_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_34_out,
        choice_33_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_33_out,
        choice_32_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_32_out,
        choice_31_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_31_out,
        choice_30_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_30_out,
        choice_29_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_29_out,
        choice_28_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_28_out,
        choice_27_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_27_out,
        choice_26_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_26_out,
        choice_25_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_25_out,
        choice_24_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_24_out,
        choice_23_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_23_out,
        choice_22_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_22_out,
        choice_21_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_21_out,
        choice_20_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_20_out,
        choice_19_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_19_out,
        choice_18_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_18_out,
        choice_17_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_17_out,
        choice_16_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_16_out,
        choice_15_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_15_out,
        choice_14_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_14_out,
        choice_13_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_13_out,
        choice_12_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_12_out,
        choice_11_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_11_out,
        choice_10_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_10_out,
        choice_9_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_9_out,
        choice_8_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_8_out,
        choice_7_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_7_out,
        choice_6_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_choice_6_out,
        prevState_V_0_10_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_10_out,
        prevState_V_1_10_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_10_out,
        prevState_V_2_4_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_4_out,
        prevState_V_3_4_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_4_out,
        prevState_V_0_4_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_4_out,
        prevState_V_1_4_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_4_out,
        prevState_V_2_10_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_10_out,
        prevState_V_3_10_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_10_out,
        prevState_V_0_9_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_9_out,
        prevState_V_1_9_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_9_out,
        prevState_V_2_3_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_3_out,
        prevState_V_3_3_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_3_out,
        prevState_V_0_3_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_3_out,
        prevState_V_1_3_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_3_out,
        prevState_V_2_9_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_9_out,
        prevState_V_3_9_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_9_out,
        prevState_V_0_8_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_8_out,
        prevState_V_1_8_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_8_out,
        prevState_V_2_2_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_2_out,
        prevState_V_3_2_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_2_out,
        prevState_V_0_2_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_2_out,
        prevState_V_1_2_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_2_out,
        prevState_V_2_8_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_8_out,
        prevState_V_3_8_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_8_out,
        prevState_V_0_7_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_7_out,
        prevState_V_1_7_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_7_out,
        prevState_V_2_1_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_1_out,
        prevState_V_3_1_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_1_out,
        prevState_V_0_1_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_1_out,
        prevState_V_1_1_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_1_out,
        prevState_V_2_7_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_7_out,
        prevState_V_3_7_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_7_out,
        prevState_V_0_6_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_6_out,
        prevState_V_1_6_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_6_out,
        prevState_V_2_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_out,
        prevState_V_3_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_out,
        prevState_V_0_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_out,
        prevState_V_1_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_out,
        prevState_V_2_6_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_6_out,
        prevState_V_3_6_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_6_out,
        prevState_V_0_11_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_11_out,
        prevState_V_1_11_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_11_out,
        prevState_V_2_5_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_5_out,
        prevState_V_3_5_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_5_out,
        prevState_V_0_5_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_0_5_out,
        prevState_V_1_5_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_1_5_out,
        prevState_V_2_11_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_2_11_out,
        prevState_V_3_11_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_prevState_V_3_11_out,
        p_Val2_1_out => grp_TrellisBuilder_Pipeline_VITIS_LOOP_1452_1_fu_711_p_Val2_1_out,
        p_Val2_1_out_ap_vld => grp_TrellisBuilder_Pipeline_VITIS_LOOP_1452_1_fu_711_p_Val2_1_out_ap_vld);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
                    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_ap_ready = ap_const_logic_1)) then 
                    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_TrellisBuilder_Pipeline_VITIS_LOOP_1452_1_fu_711_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_TrellisBuilder_Pipeline_VITIS_LOOP_1452_1_fu_711_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_TrellisBuilder_Pipeline_VITIS_LOOP_1452_1_fu_711_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_TrellisBuilder_Pipeline_VITIS_LOOP_1452_1_fu_711_ap_ready = ap_const_logic_1)) then 
                    grp_TrellisBuilder_Pipeline_VITIS_LOOP_1452_1_fu_711_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    Bucket_V_reg_579_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (not((ap_const_boolean_1 = ap_const_boolean_1))) then 
                Bucket_V_reg_579 <= ap_const_lv3_6;
            elsif (not((ap_const_boolean_1 = ap_const_boolean_1))) then 
                Bucket_V_reg_579 <= ap_const_lv3_5;
            elsif (not((ap_const_boolean_1 = ap_const_boolean_1))) then 
                Bucket_V_reg_579 <= ap_const_lv3_4;
            elsif (not((ap_const_boolean_1 = ap_const_boolean_1))) then 
                Bucket_V_reg_579 <= ap_const_lv3_3;
            elsif (not((ap_const_boolean_1 = ap_const_boolean_1))) then 
                Bucket_V_reg_579 <= ap_const_lv3_2;
            elsif (not((ap_const_boolean_1 = ap_const_boolean_1))) then 
                Bucket_V_reg_579 <= ap_const_lv3_1;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                Bucket_V_reg_579 <= ap_const_lv3_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and ((ap_const_lv6_7 = ap_const_lv6_0) or ((ap_const_lv6_A = ap_const_lv6_0) or ((ap_const_lv6_16 = ap_const_lv6_0) or ((ap_const_lv6_1B = ap_const_lv6_0) or ((ap_const_lv6_24 = ap_const_lv6_0) or ((ap_const_lv6_29 = ap_const_lv6_0) or ((ap_const_lv6_35 = ap_const_lv6_0) or (ap_const_lv6_38 = ap_const_lv6_0)))))))))) then 
                Bucket_V_reg_579 <= ap_const_lv3_7;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                p_Result_s_reg_2091 <= p_Result_s_fu_1199_p5;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_ap_done, grp_TrellisBuilder_Pipeline_VITIS_LOOP_1452_1_fu_711_ap_done, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when ap_ST_fsm_state2 => 
                if (((grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((grp_TrellisBuilder_Pipeline_VITIS_LOOP_1452_1_fu_711_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    Outdecode_o <= grp_TrellisBuilder_Pipeline_VITIS_LOOP_1452_1_fu_711_p_Val2_1_out;

    Outdecode_o_ap_vld_assign_proc : process(ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            Outdecode_o_ap_vld <= ap_const_logic_1;
        else 
            Outdecode_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_ST_fsm_state1_blk <= ap_const_logic_0;

    ap_ST_fsm_state2_blk_assign_proc : process(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_ap_done)
    begin
        if ((grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_TrellisBuilder_Pipeline_VITIS_LOOP_1452_1_fu_711_ap_done)
    begin
        if ((grp_TrellisBuilder_Pipeline_VITIS_LOOP_1452_1_fu_711_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_ap_start <= grp_TrellisBuilder_Pipeline_TrellisLoop_fu_609_ap_start_reg;
    grp_TrellisBuilder_Pipeline_VITIS_LOOP_1452_1_fu_711_ap_start <= grp_TrellisBuilder_Pipeline_VITIS_LOOP_1452_1_fu_711_ap_start_reg;
    p_Result_s_fu_1199_p5 <= (Outdecode_i(87 downto 86) & ap_const_lv2_0 & Outdecode_i(83 downto 0));
end behav;
