-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
-- Version: 2022.1
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity TrellisBuilder is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    In_EncodeStream : IN STD_LOGIC_VECTOR (23 downto 0);
    Outdecode_i : IN STD_LOGIC_VECTOR (7 downto 0);
    Outdecode_o : OUT STD_LOGIC_VECTOR (7 downto 0);
    Outdecode_o_ap_vld : OUT STD_LOGIC );
end;


architecture behav of TrellisBuilder is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "TrellisBuilder_TrellisBuilder,hls_ip_2022_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=6.360000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=5.473000,HLS_SYN_LAT=38,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=389,HLS_SYN_LUT=4084,HLS_VERSION=2022_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv3_7 : STD_LOGIC_VECTOR (2 downto 0) := "111";
    constant ap_const_lv6_38 : STD_LOGIC_VECTOR (5 downto 0) := "111000";
    constant ap_const_lv6_35 : STD_LOGIC_VECTOR (5 downto 0) := "110101";
    constant ap_const_lv6_29 : STD_LOGIC_VECTOR (5 downto 0) := "101001";
    constant ap_const_lv6_24 : STD_LOGIC_VECTOR (5 downto 0) := "100100";
    constant ap_const_lv6_1B : STD_LOGIC_VECTOR (5 downto 0) := "011011";
    constant ap_const_lv6_16 : STD_LOGIC_VECTOR (5 downto 0) := "010110";
    constant ap_const_lv6_A : STD_LOGIC_VECTOR (5 downto 0) := "001010";
    constant ap_const_lv6_7 : STD_LOGIC_VECTOR (5 downto 0) := "000111";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv6_3F : STD_LOGIC_VECTOR (5 downto 0) := "111111";
    constant ap_const_lv6_32 : STD_LOGIC_VECTOR (5 downto 0) := "110010";
    constant ap_const_lv6_2E : STD_LOGIC_VECTOR (5 downto 0) := "101110";
    constant ap_const_lv6_23 : STD_LOGIC_VECTOR (5 downto 0) := "100011";
    constant ap_const_lv6_1C : STD_LOGIC_VECTOR (5 downto 0) := "011100";
    constant ap_const_lv6_11 : STD_LOGIC_VECTOR (5 downto 0) := "010001";
    constant ap_const_lv6_D : STD_LOGIC_VECTOR (5 downto 0) := "001101";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv6_3E : STD_LOGIC_VECTOR (5 downto 0) := "111110";
    constant ap_const_lv6_33 : STD_LOGIC_VECTOR (5 downto 0) := "110011";
    constant ap_const_lv6_2F : STD_LOGIC_VECTOR (5 downto 0) := "101111";
    constant ap_const_lv6_22 : STD_LOGIC_VECTOR (5 downto 0) := "100010";
    constant ap_const_lv6_1D : STD_LOGIC_VECTOR (5 downto 0) := "011101";
    constant ap_const_lv6_10 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_const_lv6_C : STD_LOGIC_VECTOR (5 downto 0) := "001100";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_const_lv6_3D : STD_LOGIC_VECTOR (5 downto 0) := "111101";
    constant ap_const_lv6_30 : STD_LOGIC_VECTOR (5 downto 0) := "110000";
    constant ap_const_lv6_2C : STD_LOGIC_VECTOR (5 downto 0) := "101100";
    constant ap_const_lv6_21 : STD_LOGIC_VECTOR (5 downto 0) := "100001";
    constant ap_const_lv6_1E : STD_LOGIC_VECTOR (5 downto 0) := "011110";
    constant ap_const_lv6_13 : STD_LOGIC_VECTOR (5 downto 0) := "010011";
    constant ap_const_lv6_F : STD_LOGIC_VECTOR (5 downto 0) := "001111";
    constant ap_const_lv6_2 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";
    constant ap_const_lv6_3C : STD_LOGIC_VECTOR (5 downto 0) := "111100";
    constant ap_const_lv6_31 : STD_LOGIC_VECTOR (5 downto 0) := "110001";
    constant ap_const_lv6_2D : STD_LOGIC_VECTOR (5 downto 0) := "101101";
    constant ap_const_lv6_20 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv6_1F : STD_LOGIC_VECTOR (5 downto 0) := "011111";
    constant ap_const_lv6_12 : STD_LOGIC_VECTOR (5 downto 0) := "010010";
    constant ap_const_lv6_E : STD_LOGIC_VECTOR (5 downto 0) := "001110";
    constant ap_const_lv6_3 : STD_LOGIC_VECTOR (5 downto 0) := "000011";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv6_15 : STD_LOGIC_VECTOR (5 downto 0) := "010101";
    constant ap_const_lv6_3B : STD_LOGIC_VECTOR (5 downto 0) := "111011";
    constant ap_const_lv6_36 : STD_LOGIC_VECTOR (5 downto 0) := "110110";
    constant ap_const_lv6_2A : STD_LOGIC_VECTOR (5 downto 0) := "101010";
    constant ap_const_lv6_27 : STD_LOGIC_VECTOR (5 downto 0) := "100111";
    constant ap_const_lv6_18 : STD_LOGIC_VECTOR (5 downto 0) := "011000";
    constant ap_const_lv6_9 : STD_LOGIC_VECTOR (5 downto 0) := "001001";
    constant ap_const_lv6_4 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv6_3A : STD_LOGIC_VECTOR (5 downto 0) := "111010";
    constant ap_const_lv6_37 : STD_LOGIC_VECTOR (5 downto 0) := "110111";
    constant ap_const_lv6_2B : STD_LOGIC_VECTOR (5 downto 0) := "101011";
    constant ap_const_lv6_26 : STD_LOGIC_VECTOR (5 downto 0) := "100110";
    constant ap_const_lv6_19 : STD_LOGIC_VECTOR (5 downto 0) := "011001";
    constant ap_const_lv6_14 : STD_LOGIC_VECTOR (5 downto 0) := "010100";
    constant ap_const_lv6_8 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_const_lv6_5 : STD_LOGIC_VECTOR (5 downto 0) := "000101";
    constant ap_const_lv3_6 : STD_LOGIC_VECTOR (2 downto 0) := "110";
    constant ap_const_lv6_39 : STD_LOGIC_VECTOR (5 downto 0) := "111001";
    constant ap_const_lv6_34 : STD_LOGIC_VECTOR (5 downto 0) := "110100";
    constant ap_const_lv6_28 : STD_LOGIC_VECTOR (5 downto 0) := "101000";
    constant ap_const_lv6_25 : STD_LOGIC_VECTOR (5 downto 0) := "100101";
    constant ap_const_lv6_1A : STD_LOGIC_VECTOR (5 downto 0) := "011010";
    constant ap_const_lv6_17 : STD_LOGIC_VECTOR (5 downto 0) := "010111";
    constant ap_const_lv6_B : STD_LOGIC_VECTOR (5 downto 0) := "001011";
    constant ap_const_lv6_6 : STD_LOGIC_VECTOR (5 downto 0) := "000110";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal empty_fu_661_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal empty_reg_1316 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal p_Result_s_fu_866_p5 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Result_s_reg_1489 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_ap_start : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_ap_done : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_ap_idle : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_ap_ready : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_2_7_out : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_2_7_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_2_6_out : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_2_6_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_2_5_out : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_2_5_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_2_4_out : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_2_4_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_0_7_out : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_0_7_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_0_6_out : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_0_6_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_0_5_out : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_0_5_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_0_4_out : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_0_4_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_p_out : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_p_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_3_7_out : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_3_7_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_3_6_out : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_3_6_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_3_5_out : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_3_5_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_3_4_out : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_3_4_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_1_7_out : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_1_7_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_1_6_out : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_1_6_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_1_5_out : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_1_5_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_1_4_out : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_1_4_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_0_3_out : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_0_3_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_0_2_out : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_0_2_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_0_1_out : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_0_1_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_0_out : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_0_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_2_3_out : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_2_3_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_2_2_out : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_2_2_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_2_1_out : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_2_1_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_2_out : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_2_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_1_3_out : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_1_3_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_1_2_out : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_1_2_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_1_1_out : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_1_1_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_1_out : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_1_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_3_3_out : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_3_3_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_3_2_out : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_3_2_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_3_1_out : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_3_1_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_3_out : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_3_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_32_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_32_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_31_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_31_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_30_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_30_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_29_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_29_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_28_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_28_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_27_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_27_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_26_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_26_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_25_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_25_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_24_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_24_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_23_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_23_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_22_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_22_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_21_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_21_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_20_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_20_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_19_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_19_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_18_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_18_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_17_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_17_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_16_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_16_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_15_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_15_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_14_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_14_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_13_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_13_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_12_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_12_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_11_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_11_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_10_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_10_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_9_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_9_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_8_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_8_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_7_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_7_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_6_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_6_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_5_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_5_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_4_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_4_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_3_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_3_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_2_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_2_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_1_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_1_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_out_ap_vld : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_VITIS_LOOP_1453_1_fu_561_ap_start : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_VITIS_LOOP_1453_1_fu_561_ap_done : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_VITIS_LOOP_1453_1_fu_561_ap_idle : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_VITIS_LOOP_1453_1_fu_561_ap_ready : STD_LOGIC;
    signal grp_TrellisBuilder_Pipeline_VITIS_LOOP_1453_1_fu_561_p_Val2_1_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_TrellisBuilder_Pipeline_VITIS_LOOP_1453_1_fu_561_p_Val2_1_out_ap_vld : STD_LOGIC;
    signal ap_phi_mux_Bucket_V_phi_fu_462_p16 : STD_LOGIC_VECTOR (2 downto 0);
    signal Bucket_V_reg_459 : STD_LOGIC_VECTOR (2 downto 0);
    signal p_loc_load_load_fu_658_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_TrellisBuilder_Pipeline_VITIS_LOOP_1453_1_fu_561_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal p_Repl2_s_fu_836_p10 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_12_fu_858_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_condition_275 : BOOLEAN;
    signal ap_condition_300 : BOOLEAN;
    signal ap_condition_325 : BOOLEAN;
    signal ap_condition_350 : BOOLEAN;
    signal ap_condition_375 : BOOLEAN;
    signal ap_condition_400 : BOOLEAN;
    signal ap_condition_425 : BOOLEAN;
    signal ap_condition_450 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component TrellisBuilder_TrellisBuilder_Pipeline_TrellisLoop IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        In_EncodeStream : IN STD_LOGIC_VECTOR (23 downto 0);
        prevState_V_2_7_out : OUT STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_2_7_out_ap_vld : OUT STD_LOGIC;
        prevState_V_2_6_out : OUT STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_2_6_out_ap_vld : OUT STD_LOGIC;
        prevState_V_2_5_out : OUT STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_2_5_out_ap_vld : OUT STD_LOGIC;
        prevState_V_2_4_out : OUT STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_2_4_out_ap_vld : OUT STD_LOGIC;
        prevState_V_0_7_out : OUT STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_0_7_out_ap_vld : OUT STD_LOGIC;
        prevState_V_0_6_out : OUT STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_0_6_out_ap_vld : OUT STD_LOGIC;
        prevState_V_0_5_out : OUT STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_0_5_out_ap_vld : OUT STD_LOGIC;
        prevState_V_0_4_out : OUT STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_0_4_out_ap_vld : OUT STD_LOGIC;
        p_out : OUT STD_LOGIC_VECTOR (5 downto 0);
        p_out_ap_vld : OUT STD_LOGIC;
        prevState_V_3_7_out : OUT STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_3_7_out_ap_vld : OUT STD_LOGIC;
        prevState_V_3_6_out : OUT STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_3_6_out_ap_vld : OUT STD_LOGIC;
        prevState_V_3_5_out : OUT STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_3_5_out_ap_vld : OUT STD_LOGIC;
        prevState_V_3_4_out : OUT STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_3_4_out_ap_vld : OUT STD_LOGIC;
        prevState_V_1_7_out : OUT STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_1_7_out_ap_vld : OUT STD_LOGIC;
        prevState_V_1_6_out : OUT STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_1_6_out_ap_vld : OUT STD_LOGIC;
        prevState_V_1_5_out : OUT STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_1_5_out_ap_vld : OUT STD_LOGIC;
        prevState_V_1_4_out : OUT STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_1_4_out_ap_vld : OUT STD_LOGIC;
        prevState_V_0_3_out : OUT STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_0_3_out_ap_vld : OUT STD_LOGIC;
        prevState_V_0_2_out : OUT STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_0_2_out_ap_vld : OUT STD_LOGIC;
        prevState_V_0_1_out : OUT STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_0_1_out_ap_vld : OUT STD_LOGIC;
        prevState_V_0_out : OUT STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_0_out_ap_vld : OUT STD_LOGIC;
        prevState_V_2_3_out : OUT STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_2_3_out_ap_vld : OUT STD_LOGIC;
        prevState_V_2_2_out : OUT STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_2_2_out_ap_vld : OUT STD_LOGIC;
        prevState_V_2_1_out : OUT STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_2_1_out_ap_vld : OUT STD_LOGIC;
        prevState_V_2_out : OUT STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_2_out_ap_vld : OUT STD_LOGIC;
        prevState_V_1_3_out : OUT STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_1_3_out_ap_vld : OUT STD_LOGIC;
        prevState_V_1_2_out : OUT STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_1_2_out_ap_vld : OUT STD_LOGIC;
        prevState_V_1_1_out : OUT STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_1_1_out_ap_vld : OUT STD_LOGIC;
        prevState_V_1_out : OUT STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_1_out_ap_vld : OUT STD_LOGIC;
        prevState_V_3_3_out : OUT STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_3_3_out_ap_vld : OUT STD_LOGIC;
        prevState_V_3_2_out : OUT STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_3_2_out_ap_vld : OUT STD_LOGIC;
        prevState_V_3_1_out : OUT STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_3_1_out_ap_vld : OUT STD_LOGIC;
        prevState_V_3_out : OUT STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_3_out_ap_vld : OUT STD_LOGIC;
        choice_32_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        choice_32_out_ap_vld : OUT STD_LOGIC;
        choice_31_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        choice_31_out_ap_vld : OUT STD_LOGIC;
        choice_30_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        choice_30_out_ap_vld : OUT STD_LOGIC;
        choice_29_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        choice_29_out_ap_vld : OUT STD_LOGIC;
        choice_28_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        choice_28_out_ap_vld : OUT STD_LOGIC;
        choice_27_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        choice_27_out_ap_vld : OUT STD_LOGIC;
        choice_26_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        choice_26_out_ap_vld : OUT STD_LOGIC;
        choice_25_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        choice_25_out_ap_vld : OUT STD_LOGIC;
        choice_24_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        choice_24_out_ap_vld : OUT STD_LOGIC;
        choice_23_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        choice_23_out_ap_vld : OUT STD_LOGIC;
        choice_22_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        choice_22_out_ap_vld : OUT STD_LOGIC;
        choice_21_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        choice_21_out_ap_vld : OUT STD_LOGIC;
        choice_20_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        choice_20_out_ap_vld : OUT STD_LOGIC;
        choice_19_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        choice_19_out_ap_vld : OUT STD_LOGIC;
        choice_18_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        choice_18_out_ap_vld : OUT STD_LOGIC;
        choice_17_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        choice_17_out_ap_vld : OUT STD_LOGIC;
        choice_16_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        choice_16_out_ap_vld : OUT STD_LOGIC;
        choice_15_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        choice_15_out_ap_vld : OUT STD_LOGIC;
        choice_14_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        choice_14_out_ap_vld : OUT STD_LOGIC;
        choice_13_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        choice_13_out_ap_vld : OUT STD_LOGIC;
        choice_12_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        choice_12_out_ap_vld : OUT STD_LOGIC;
        choice_11_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        choice_11_out_ap_vld : OUT STD_LOGIC;
        choice_10_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        choice_10_out_ap_vld : OUT STD_LOGIC;
        choice_9_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        choice_9_out_ap_vld : OUT STD_LOGIC;
        choice_8_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        choice_8_out_ap_vld : OUT STD_LOGIC;
        choice_7_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        choice_7_out_ap_vld : OUT STD_LOGIC;
        choice_6_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        choice_6_out_ap_vld : OUT STD_LOGIC;
        choice_5_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        choice_5_out_ap_vld : OUT STD_LOGIC;
        choice_4_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        choice_4_out_ap_vld : OUT STD_LOGIC;
        choice_3_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        choice_3_out_ap_vld : OUT STD_LOGIC;
        choice_2_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        choice_2_out_ap_vld : OUT STD_LOGIC;
        choice_1_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        choice_1_out_ap_vld : OUT STD_LOGIC;
        choice_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        choice_out_ap_vld : OUT STD_LOGIC );
    end component;


    component TrellisBuilder_TrellisBuilder_Pipeline_VITIS_LOOP_1453_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        p_Result_s : IN STD_LOGIC_VECTOR (7 downto 0);
        p_reload : IN STD_LOGIC_VECTOR (2 downto 0);
        Bucket_V : IN STD_LOGIC_VECTOR (2 downto 0);
        choice_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        choice_1_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        choice_2_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        choice_3_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        choice_9_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        choice_10_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        choice_11_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        choice_12_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        choice_17_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        choice_18_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        choice_19_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        choice_20_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        choice_25_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        choice_26_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        choice_27_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        choice_28_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        choice_32_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        choice_31_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        choice_30_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        choice_29_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        choice_24_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        choice_23_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        choice_22_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        choice_21_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        choice_16_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        choice_15_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        choice_14_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        choice_13_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        choice_8_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        choice_7_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        choice_6_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        choice_5_reload : IN STD_LOGIC_VECTOR (0 downto 0);
        prevState_V_0_7_reload : IN STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_1_7_reload : IN STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_2_3_reload : IN STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_3_3_reload : IN STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_0_3_reload : IN STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_1_3_reload : IN STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_2_7_reload : IN STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_3_7_reload : IN STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_0_6_reload : IN STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_1_6_reload : IN STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_2_2_reload : IN STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_3_2_reload : IN STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_0_2_reload : IN STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_1_2_reload : IN STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_2_6_reload : IN STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_3_6_reload : IN STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_0_5_reload : IN STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_1_5_reload : IN STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_2_1_reload : IN STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_3_1_reload : IN STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_0_1_reload : IN STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_1_1_reload : IN STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_2_5_reload : IN STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_3_5_reload : IN STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_0_4_reload : IN STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_1_4_reload : IN STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_2_reload : IN STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_3_reload : IN STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_0_reload : IN STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_1_reload : IN STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_2_4_reload : IN STD_LOGIC_VECTOR (5 downto 0);
        prevState_V_3_4_reload : IN STD_LOGIC_VECTOR (5 downto 0);
        p_Val2_1_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_Val2_1_out_ap_vld : OUT STD_LOGIC );
    end component;


    component TrellisBuilder_mux_83_1_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        din4_WIDTH : INTEGER;
        din5_WIDTH : INTEGER;
        din6_WIDTH : INTEGER;
        din7_WIDTH : INTEGER;
        din8_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (0 downto 0);
        din1 : IN STD_LOGIC_VECTOR (0 downto 0);
        din2 : IN STD_LOGIC_VECTOR (0 downto 0);
        din3 : IN STD_LOGIC_VECTOR (0 downto 0);
        din4 : IN STD_LOGIC_VECTOR (0 downto 0);
        din5 : IN STD_LOGIC_VECTOR (0 downto 0);
        din6 : IN STD_LOGIC_VECTOR (0 downto 0);
        din7 : IN STD_LOGIC_VECTOR (0 downto 0);
        din8 : IN STD_LOGIC_VECTOR (2 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;



begin
    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489 : component TrellisBuilder_TrellisBuilder_Pipeline_TrellisLoop
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_ap_start,
        ap_done => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_ap_done,
        ap_idle => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_ap_idle,
        ap_ready => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_ap_ready,
        In_EncodeStream => In_EncodeStream,
        prevState_V_2_7_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_2_7_out,
        prevState_V_2_7_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_2_7_out_ap_vld,
        prevState_V_2_6_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_2_6_out,
        prevState_V_2_6_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_2_6_out_ap_vld,
        prevState_V_2_5_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_2_5_out,
        prevState_V_2_5_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_2_5_out_ap_vld,
        prevState_V_2_4_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_2_4_out,
        prevState_V_2_4_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_2_4_out_ap_vld,
        prevState_V_0_7_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_0_7_out,
        prevState_V_0_7_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_0_7_out_ap_vld,
        prevState_V_0_6_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_0_6_out,
        prevState_V_0_6_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_0_6_out_ap_vld,
        prevState_V_0_5_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_0_5_out,
        prevState_V_0_5_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_0_5_out_ap_vld,
        prevState_V_0_4_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_0_4_out,
        prevState_V_0_4_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_0_4_out_ap_vld,
        p_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_p_out,
        p_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_p_out_ap_vld,
        prevState_V_3_7_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_3_7_out,
        prevState_V_3_7_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_3_7_out_ap_vld,
        prevState_V_3_6_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_3_6_out,
        prevState_V_3_6_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_3_6_out_ap_vld,
        prevState_V_3_5_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_3_5_out,
        prevState_V_3_5_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_3_5_out_ap_vld,
        prevState_V_3_4_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_3_4_out,
        prevState_V_3_4_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_3_4_out_ap_vld,
        prevState_V_1_7_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_1_7_out,
        prevState_V_1_7_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_1_7_out_ap_vld,
        prevState_V_1_6_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_1_6_out,
        prevState_V_1_6_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_1_6_out_ap_vld,
        prevState_V_1_5_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_1_5_out,
        prevState_V_1_5_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_1_5_out_ap_vld,
        prevState_V_1_4_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_1_4_out,
        prevState_V_1_4_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_1_4_out_ap_vld,
        prevState_V_0_3_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_0_3_out,
        prevState_V_0_3_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_0_3_out_ap_vld,
        prevState_V_0_2_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_0_2_out,
        prevState_V_0_2_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_0_2_out_ap_vld,
        prevState_V_0_1_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_0_1_out,
        prevState_V_0_1_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_0_1_out_ap_vld,
        prevState_V_0_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_0_out,
        prevState_V_0_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_0_out_ap_vld,
        prevState_V_2_3_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_2_3_out,
        prevState_V_2_3_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_2_3_out_ap_vld,
        prevState_V_2_2_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_2_2_out,
        prevState_V_2_2_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_2_2_out_ap_vld,
        prevState_V_2_1_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_2_1_out,
        prevState_V_2_1_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_2_1_out_ap_vld,
        prevState_V_2_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_2_out,
        prevState_V_2_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_2_out_ap_vld,
        prevState_V_1_3_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_1_3_out,
        prevState_V_1_3_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_1_3_out_ap_vld,
        prevState_V_1_2_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_1_2_out,
        prevState_V_1_2_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_1_2_out_ap_vld,
        prevState_V_1_1_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_1_1_out,
        prevState_V_1_1_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_1_1_out_ap_vld,
        prevState_V_1_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_1_out,
        prevState_V_1_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_1_out_ap_vld,
        prevState_V_3_3_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_3_3_out,
        prevState_V_3_3_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_3_3_out_ap_vld,
        prevState_V_3_2_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_3_2_out,
        prevState_V_3_2_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_3_2_out_ap_vld,
        prevState_V_3_1_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_3_1_out,
        prevState_V_3_1_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_3_1_out_ap_vld,
        prevState_V_3_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_3_out,
        prevState_V_3_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_3_out_ap_vld,
        choice_32_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_32_out,
        choice_32_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_32_out_ap_vld,
        choice_31_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_31_out,
        choice_31_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_31_out_ap_vld,
        choice_30_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_30_out,
        choice_30_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_30_out_ap_vld,
        choice_29_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_29_out,
        choice_29_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_29_out_ap_vld,
        choice_28_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_28_out,
        choice_28_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_28_out_ap_vld,
        choice_27_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_27_out,
        choice_27_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_27_out_ap_vld,
        choice_26_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_26_out,
        choice_26_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_26_out_ap_vld,
        choice_25_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_25_out,
        choice_25_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_25_out_ap_vld,
        choice_24_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_24_out,
        choice_24_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_24_out_ap_vld,
        choice_23_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_23_out,
        choice_23_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_23_out_ap_vld,
        choice_22_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_22_out,
        choice_22_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_22_out_ap_vld,
        choice_21_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_21_out,
        choice_21_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_21_out_ap_vld,
        choice_20_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_20_out,
        choice_20_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_20_out_ap_vld,
        choice_19_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_19_out,
        choice_19_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_19_out_ap_vld,
        choice_18_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_18_out,
        choice_18_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_18_out_ap_vld,
        choice_17_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_17_out,
        choice_17_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_17_out_ap_vld,
        choice_16_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_16_out,
        choice_16_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_16_out_ap_vld,
        choice_15_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_15_out,
        choice_15_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_15_out_ap_vld,
        choice_14_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_14_out,
        choice_14_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_14_out_ap_vld,
        choice_13_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_13_out,
        choice_13_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_13_out_ap_vld,
        choice_12_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_12_out,
        choice_12_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_12_out_ap_vld,
        choice_11_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_11_out,
        choice_11_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_11_out_ap_vld,
        choice_10_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_10_out,
        choice_10_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_10_out_ap_vld,
        choice_9_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_9_out,
        choice_9_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_9_out_ap_vld,
        choice_8_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_8_out,
        choice_8_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_8_out_ap_vld,
        choice_7_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_7_out,
        choice_7_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_7_out_ap_vld,
        choice_6_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_6_out,
        choice_6_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_6_out_ap_vld,
        choice_5_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_5_out,
        choice_5_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_5_out_ap_vld,
        choice_4_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_4_out,
        choice_4_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_4_out_ap_vld,
        choice_3_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_3_out,
        choice_3_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_3_out_ap_vld,
        choice_2_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_2_out,
        choice_2_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_2_out_ap_vld,
        choice_1_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_1_out,
        choice_1_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_1_out_ap_vld,
        choice_out => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_out,
        choice_out_ap_vld => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_out_ap_vld);

    grp_TrellisBuilder_Pipeline_VITIS_LOOP_1453_1_fu_561 : component TrellisBuilder_TrellisBuilder_Pipeline_VITIS_LOOP_1453_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_TrellisBuilder_Pipeline_VITIS_LOOP_1453_1_fu_561_ap_start,
        ap_done => grp_TrellisBuilder_Pipeline_VITIS_LOOP_1453_1_fu_561_ap_done,
        ap_idle => grp_TrellisBuilder_Pipeline_VITIS_LOOP_1453_1_fu_561_ap_idle,
        ap_ready => grp_TrellisBuilder_Pipeline_VITIS_LOOP_1453_1_fu_561_ap_ready,
        p_Result_s => p_Result_s_reg_1489,
        p_reload => empty_reg_1316,
        Bucket_V => Bucket_V_reg_459,
        choice_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_out,
        choice_1_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_1_out,
        choice_2_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_2_out,
        choice_3_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_3_out,
        choice_9_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_9_out,
        choice_10_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_10_out,
        choice_11_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_11_out,
        choice_12_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_12_out,
        choice_17_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_17_out,
        choice_18_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_18_out,
        choice_19_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_19_out,
        choice_20_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_20_out,
        choice_25_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_25_out,
        choice_26_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_26_out,
        choice_27_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_27_out,
        choice_28_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_28_out,
        choice_32_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_32_out,
        choice_31_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_31_out,
        choice_30_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_30_out,
        choice_29_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_29_out,
        choice_24_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_24_out,
        choice_23_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_23_out,
        choice_22_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_22_out,
        choice_21_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_21_out,
        choice_16_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_16_out,
        choice_15_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_15_out,
        choice_14_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_14_out,
        choice_13_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_13_out,
        choice_8_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_8_out,
        choice_7_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_7_out,
        choice_6_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_6_out,
        choice_5_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_5_out,
        prevState_V_0_7_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_0_7_out,
        prevState_V_1_7_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_1_7_out,
        prevState_V_2_3_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_2_3_out,
        prevState_V_3_3_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_3_3_out,
        prevState_V_0_3_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_0_3_out,
        prevState_V_1_3_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_1_3_out,
        prevState_V_2_7_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_2_7_out,
        prevState_V_3_7_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_3_7_out,
        prevState_V_0_6_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_0_6_out,
        prevState_V_1_6_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_1_6_out,
        prevState_V_2_2_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_2_2_out,
        prevState_V_3_2_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_3_2_out,
        prevState_V_0_2_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_0_2_out,
        prevState_V_1_2_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_1_2_out,
        prevState_V_2_6_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_2_6_out,
        prevState_V_3_6_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_3_6_out,
        prevState_V_0_5_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_0_5_out,
        prevState_V_1_5_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_1_5_out,
        prevState_V_2_1_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_2_1_out,
        prevState_V_3_1_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_3_1_out,
        prevState_V_0_1_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_0_1_out,
        prevState_V_1_1_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_1_1_out,
        prevState_V_2_5_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_2_5_out,
        prevState_V_3_5_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_3_5_out,
        prevState_V_0_4_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_0_4_out,
        prevState_V_1_4_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_1_4_out,
        prevState_V_2_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_2_out,
        prevState_V_3_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_3_out,
        prevState_V_0_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_0_out,
        prevState_V_1_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_1_out,
        prevState_V_2_4_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_2_4_out,
        prevState_V_3_4_reload => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_prevState_V_3_4_out,
        p_Val2_1_out => grp_TrellisBuilder_Pipeline_VITIS_LOOP_1453_1_fu_561_p_Val2_1_out,
        p_Val2_1_out_ap_vld => grp_TrellisBuilder_Pipeline_VITIS_LOOP_1453_1_fu_561_p_Val2_1_out_ap_vld);

    mux_83_1_1_1_U163 : component TrellisBuilder_mux_83_1_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 1,
        din1_WIDTH => 1,
        din2_WIDTH => 1,
        din3_WIDTH => 1,
        din4_WIDTH => 1,
        din5_WIDTH => 1,
        din6_WIDTH => 1,
        din7_WIDTH => 1,
        din8_WIDTH => 3,
        dout_WIDTH => 1)
    port map (
        din0 => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_3_out,
        din1 => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_12_out,
        din2 => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_20_out,
        din3 => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_28_out,
        din4 => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_29_out,
        din5 => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_21_out,
        din6 => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_13_out,
        din7 => grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_5_out,
        din8 => ap_phi_mux_Bucket_V_phi_fu_462_p16,
        dout => p_Repl2_s_fu_836_p10);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
                    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_ap_ready = ap_const_logic_1)) then 
                    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_TrellisBuilder_Pipeline_VITIS_LOOP_1453_1_fu_561_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_TrellisBuilder_Pipeline_VITIS_LOOP_1453_1_fu_561_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                    grp_TrellisBuilder_Pipeline_VITIS_LOOP_1453_1_fu_561_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_TrellisBuilder_Pipeline_VITIS_LOOP_1453_1_fu_561_ap_ready = ap_const_logic_1)) then 
                    grp_TrellisBuilder_Pipeline_VITIS_LOOP_1453_1_fu_561_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    Bucket_V_reg_459_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                if ((ap_const_boolean_1 = ap_condition_450)) then 
                    Bucket_V_reg_459 <= ap_const_lv3_6;
                elsif ((ap_const_boolean_1 = ap_condition_425)) then 
                    Bucket_V_reg_459 <= ap_const_lv3_5;
                elsif ((ap_const_boolean_1 = ap_condition_400)) then 
                    Bucket_V_reg_459 <= ap_const_lv3_4;
                elsif ((ap_const_boolean_1 = ap_condition_375)) then 
                    Bucket_V_reg_459 <= ap_const_lv3_3;
                elsif ((ap_const_boolean_1 = ap_condition_350)) then 
                    Bucket_V_reg_459 <= ap_const_lv3_2;
                elsif ((ap_const_boolean_1 = ap_condition_325)) then 
                    Bucket_V_reg_459 <= ap_const_lv3_1;
                elsif ((ap_const_boolean_1 = ap_condition_300)) then 
                    Bucket_V_reg_459 <= ap_const_lv3_0;
                elsif ((ap_const_boolean_1 = ap_condition_275)) then 
                    Bucket_V_reg_459 <= ap_const_lv3_7;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                empty_reg_1316 <= empty_fu_661_p1;
                p_Result_s_reg_1489 <= p_Result_s_fu_866_p5;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_ap_done, grp_TrellisBuilder_Pipeline_VITIS_LOOP_1453_1_fu_561_ap_done, ap_CS_fsm_state2, ap_CS_fsm_state5)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when ap_ST_fsm_state2 => 
                if (((grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state5) and (grp_TrellisBuilder_Pipeline_VITIS_LOOP_1453_1_fu_561_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXX";
        end case;
    end process;
    Outdecode_o <= grp_TrellisBuilder_Pipeline_VITIS_LOOP_1453_1_fu_561_p_Val2_1_out;

    Outdecode_o_ap_vld_assign_proc : process(ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            Outdecode_o_ap_vld <= ap_const_logic_1;
        else 
            Outdecode_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_ST_fsm_state1_blk <= ap_const_logic_0;

    ap_ST_fsm_state2_blk_assign_proc : process(grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_ap_done)
    begin
        if ((grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;

    ap_ST_fsm_state5_blk_assign_proc : process(grp_TrellisBuilder_Pipeline_VITIS_LOOP_1453_1_fu_561_ap_done)
    begin
        if ((grp_TrellisBuilder_Pipeline_VITIS_LOOP_1453_1_fu_561_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state6_blk <= ap_const_logic_0;

    ap_condition_275_assign_proc : process(p_loc_load_load_fu_658_p1)
    begin
                ap_condition_275 <= ((p_loc_load_load_fu_658_p1 = ap_const_lv6_7) or ((p_loc_load_load_fu_658_p1 = ap_const_lv6_A) or ((p_loc_load_load_fu_658_p1 = ap_const_lv6_16) or ((p_loc_load_load_fu_658_p1 = ap_const_lv6_1B) or ((p_loc_load_load_fu_658_p1 = ap_const_lv6_24) or ((p_loc_load_load_fu_658_p1 = ap_const_lv6_29) or ((p_loc_load_load_fu_658_p1 = ap_const_lv6_35) or (p_loc_load_load_fu_658_p1 = ap_const_lv6_38))))))));
    end process;


    ap_condition_300_assign_proc : process(p_loc_load_load_fu_658_p1)
    begin
                ap_condition_300 <= ((p_loc_load_load_fu_658_p1 = ap_const_lv6_0) or ((p_loc_load_load_fu_658_p1 = ap_const_lv6_D) or ((p_loc_load_load_fu_658_p1 = ap_const_lv6_11) or ((p_loc_load_load_fu_658_p1 = ap_const_lv6_1C) or ((p_loc_load_load_fu_658_p1 = ap_const_lv6_23) or ((p_loc_load_load_fu_658_p1 = ap_const_lv6_2E) or ((p_loc_load_load_fu_658_p1 = ap_const_lv6_32) or (p_loc_load_load_fu_658_p1 = ap_const_lv6_3F))))))));
    end process;


    ap_condition_325_assign_proc : process(p_loc_load_load_fu_658_p1)
    begin
                ap_condition_325 <= ((p_loc_load_load_fu_658_p1 = ap_const_lv6_1) or ((p_loc_load_load_fu_658_p1 = ap_const_lv6_C) or ((p_loc_load_load_fu_658_p1 = ap_const_lv6_10) or ((p_loc_load_load_fu_658_p1 = ap_const_lv6_1D) or ((p_loc_load_load_fu_658_p1 = ap_const_lv6_22) or ((p_loc_load_load_fu_658_p1 = ap_const_lv6_2F) or ((p_loc_load_load_fu_658_p1 = ap_const_lv6_33) or (p_loc_load_load_fu_658_p1 = ap_const_lv6_3E))))))));
    end process;


    ap_condition_350_assign_proc : process(p_loc_load_load_fu_658_p1)
    begin
                ap_condition_350 <= ((p_loc_load_load_fu_658_p1 = ap_const_lv6_2) or ((p_loc_load_load_fu_658_p1 = ap_const_lv6_F) or ((p_loc_load_load_fu_658_p1 = ap_const_lv6_13) or ((p_loc_load_load_fu_658_p1 = ap_const_lv6_1E) or ((p_loc_load_load_fu_658_p1 = ap_const_lv6_21) or ((p_loc_load_load_fu_658_p1 = ap_const_lv6_2C) or ((p_loc_load_load_fu_658_p1 = ap_const_lv6_30) or (p_loc_load_load_fu_658_p1 = ap_const_lv6_3D))))))));
    end process;


    ap_condition_375_assign_proc : process(p_loc_load_load_fu_658_p1)
    begin
                ap_condition_375 <= ((p_loc_load_load_fu_658_p1 = ap_const_lv6_3) or ((p_loc_load_load_fu_658_p1 = ap_const_lv6_E) or ((p_loc_load_load_fu_658_p1 = ap_const_lv6_12) or ((p_loc_load_load_fu_658_p1 = ap_const_lv6_1F) or ((p_loc_load_load_fu_658_p1 = ap_const_lv6_20) or ((p_loc_load_load_fu_658_p1 = ap_const_lv6_2D) or ((p_loc_load_load_fu_658_p1 = ap_const_lv6_31) or (p_loc_load_load_fu_658_p1 = ap_const_lv6_3C))))))));
    end process;


    ap_condition_400_assign_proc : process(p_loc_load_load_fu_658_p1)
    begin
                ap_condition_400 <= ((p_loc_load_load_fu_658_p1 = ap_const_lv6_4) or ((p_loc_load_load_fu_658_p1 = ap_const_lv6_9) or ((p_loc_load_load_fu_658_p1 = ap_const_lv6_18) or ((p_loc_load_load_fu_658_p1 = ap_const_lv6_27) or ((p_loc_load_load_fu_658_p1 = ap_const_lv6_2A) or ((p_loc_load_load_fu_658_p1 = ap_const_lv6_36) or ((p_loc_load_load_fu_658_p1 = ap_const_lv6_3B) or (p_loc_load_load_fu_658_p1 = ap_const_lv6_15))))))));
    end process;


    ap_condition_425_assign_proc : process(p_loc_load_load_fu_658_p1)
    begin
                ap_condition_425 <= ((p_loc_load_load_fu_658_p1 = ap_const_lv6_5) or ((p_loc_load_load_fu_658_p1 = ap_const_lv6_8) or ((p_loc_load_load_fu_658_p1 = ap_const_lv6_14) or ((p_loc_load_load_fu_658_p1 = ap_const_lv6_19) or ((p_loc_load_load_fu_658_p1 = ap_const_lv6_26) or ((p_loc_load_load_fu_658_p1 = ap_const_lv6_2B) or ((p_loc_load_load_fu_658_p1 = ap_const_lv6_37) or (p_loc_load_load_fu_658_p1 = ap_const_lv6_3A))))))));
    end process;


    ap_condition_450_assign_proc : process(p_loc_load_load_fu_658_p1)
    begin
                ap_condition_450 <= ((p_loc_load_load_fu_658_p1 = ap_const_lv6_6) or ((p_loc_load_load_fu_658_p1 = ap_const_lv6_B) or ((p_loc_load_load_fu_658_p1 = ap_const_lv6_17) or ((p_loc_load_load_fu_658_p1 = ap_const_lv6_1A) or ((p_loc_load_load_fu_658_p1 = ap_const_lv6_25) or ((p_loc_load_load_fu_658_p1 = ap_const_lv6_28) or ((p_loc_load_load_fu_658_p1 = ap_const_lv6_34) or (p_loc_load_load_fu_658_p1 = ap_const_lv6_39))))))));
    end process;


    ap_phi_mux_Bucket_V_phi_fu_462_p16_assign_proc : process(ap_CS_fsm_state3, ap_condition_275, ap_condition_300, ap_condition_325, ap_condition_350, ap_condition_375, ap_condition_400, ap_condition_425, ap_condition_450)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
            if ((ap_const_boolean_1 = ap_condition_450)) then 
                ap_phi_mux_Bucket_V_phi_fu_462_p16 <= ap_const_lv3_6;
            elsif ((ap_const_boolean_1 = ap_condition_425)) then 
                ap_phi_mux_Bucket_V_phi_fu_462_p16 <= ap_const_lv3_5;
            elsif ((ap_const_boolean_1 = ap_condition_400)) then 
                ap_phi_mux_Bucket_V_phi_fu_462_p16 <= ap_const_lv3_4;
            elsif ((ap_const_boolean_1 = ap_condition_375)) then 
                ap_phi_mux_Bucket_V_phi_fu_462_p16 <= ap_const_lv3_3;
            elsif ((ap_const_boolean_1 = ap_condition_350)) then 
                ap_phi_mux_Bucket_V_phi_fu_462_p16 <= ap_const_lv3_2;
            elsif ((ap_const_boolean_1 = ap_condition_325)) then 
                ap_phi_mux_Bucket_V_phi_fu_462_p16 <= ap_const_lv3_1;
            elsif ((ap_const_boolean_1 = ap_condition_300)) then 
                ap_phi_mux_Bucket_V_phi_fu_462_p16 <= ap_const_lv3_0;
            elsif ((ap_const_boolean_1 = ap_condition_275)) then 
                ap_phi_mux_Bucket_V_phi_fu_462_p16 <= ap_const_lv3_7;
            else 
                ap_phi_mux_Bucket_V_phi_fu_462_p16 <= "XXX";
            end if;
        else 
            ap_phi_mux_Bucket_V_phi_fu_462_p16 <= "XXX";
        end if; 
    end process;

    empty_fu_661_p1 <= grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_p_out(3 - 1 downto 0);
    grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_ap_start <= grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_ap_start_reg;
    grp_TrellisBuilder_Pipeline_VITIS_LOOP_1453_1_fu_561_ap_start <= grp_TrellisBuilder_Pipeline_VITIS_LOOP_1453_1_fu_561_ap_start_reg;
    p_Result_s_fu_866_p5 <= (Outdecode_i(7 downto 6) & tmp_12_fu_858_p3 & Outdecode_i(3 downto 0));
    p_loc_load_load_fu_658_p1 <= grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_p_out;
    tmp_12_fu_858_p3 <= (grp_TrellisBuilder_Pipeline_TrellisLoop_fu_489_choice_4_out & p_Repl2_s_fu_836_p10);
end behav;
